name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # At midnight on the 1st day of each month
env:
  IMAGE: kartaltabak/python-with-jenkins-user
  TEST_TAG: kartaltabak/python-with-jenkins-user:test
  LATEST_TAG: kartaltabak/python-with-jenkins-user:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up date for tagging
        run: echo "DATE_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push Docker image with timestamp
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Run Docker test command
        run: |
          docker run --rm ${{ env.TEST_TAG }} python --help

      - name: Build and push Docker image with timestamp
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ env.DATE_TAG }}
            ${{ env.IMAGE }}:latest
